package com.ka4piece.controller;

import com.ka4piece.manager.AuthManager;
import com.ka4piece.model.Household;
import com.ka4piece.utilities.PasswordUtil;
import com.ka4piece.utilities.IdUtil;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class RegisterHouseholdController {

    private AuthManager authManager;

    // Constructor injection
    public RegisterHouseholdController(AuthManager authManager) {
        this.authManager = authManager;
    }

    @FXML
    private TextField txtHeadName;
    @FXML
    private TextField txtAddress;
    @FXML
    private TextField txtBarangay;
    @FXML
    private TextField txtEmailField;
    @FXML
    private TextField txtIdField;
    @FXML
    private Button btnRegister;
    @FXML
    private Label lblSuccessMessage;

    @FXML
    private void handleRegister(ActionEvent event) {
        try {
            // 1. Extract and clean input values from registration form
            String headName = txtHeadName.getText().trim();
            String address = txtAddress.getText().trim();
            String barangay = txtBarangay.getText().trim();
            String email = txtEmailField.getText().trim();

            // 2. Checks if all required fields are filled in
            if (headName.isEmpty() || email.isEmpty() || address.isEmpty() || barangay.isEmpty()) {
                if (lblSuccessMessage != null) {
                    lblSuccessMessage.setText("Please fill in all required fields.");
                    lblSuccessMessage.setVisible(true);
                }
                return;
            }

            // 3. Generate and store generatedId to be displayed in success later
            String generatedId = IdUtil.generateId("HH");

            // 4. Create new Household object (householdId will be auto-generated by IdUtil)
            Household newHousehold = new Household(generatedId, headName, address, barangay, email,
                    PasswordUtil.generateTemporaryPassword());

            // 5. Register the household
            authManager.registerHousehold(newHousehold);

            // 6. Display Sucess Message with generated ID
            if (lblSuccessMessage != null) {
                lblSuccessMessage.setText("Household registered successfully: " + generatedId);
                lblSuccessMessage.setVisible(true);
            }

            // 7. Disable register button after registration while modal stays open for
            // review
            if (btnRegister != null) {
                btnRegister.setDisable(true);
            }

        //8. Complete catching of errors with dedicated messages: Clean message in UI, full trace in console
        } catch (IllegalArgumentException e) {
            // Business rule violation (e.g. duplicate email)
            System.err.println("[RegisterHousehold] Validation error: " + e.getMessage());
            showError(e.getMessage());

        } catch (RuntimeException e) {
            // DB failure bubbled up from Repositories
            System.err.println("[RegisterHousehold] Database error during registration: " + e.getMessage());
            e.printStackTrace();
            showError("A database error occurred. Please contact support.");

        } catch (Exception e) {
            // Unexpected fallback (e.g. NPE from FXML binding failure)
            System.err.println("[RegisterHousehold] Unexpected error: " + e.getMessage());
            e.printStackTrace();
            showError("An unexpected error occurred. Please try again.");
        }
    }

    // helper file to print error messages
    private void showError(String message) {
        if (lblSuccessMessage != null) {
            lblSuccessMessage.setText(message);
            lblSuccessMessage.setVisible(true);
        }
    }
}